name: flutter_cupertino_date_picker
description: Flutter cupertino date picker. Display DatePicker in iOS style. Support both Android and iOS platform.
version: 1.0.26+2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.3 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

